[theme]
primaryColor = "#00b894"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#1e1e30"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5

[browser]
gatherUsageStats = false
